import { GeistSans } from 'geist/font/sans';
import './globals.css';
import Header from '@/components/Header';
import classNames from 'classnames';

export const metadata = {
  title: 'murat can kirdar',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={classNames(GeistSans.className, 'flex flex-row justify-center')}>
        <div className={classNames('w-full p-4')}>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
